import Header from "@/components/Marginalia/Header";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const cookieValue = cookieStore.get("SpooCookie")?.value;
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-black flex flex-col min-h-screen`}
      >
        <Header cookieValue={cookieValue} />
        {children}
      </body>
    </html>
  );
}
